version: '3.9'

services:
  web:
    build:
      context: .  # Path to your project directory
    ports:
      - "3000:3000"  # Expose port 3000 to the host machine
    environment:
      - GOOGLE_ID=260802364381-ufaost9i64q3r7kidrjt0a87nqsu83rs.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - MONGODB_URI=mongodb+srv://amitabhsoni2004:amitabh@2004@cluster0.xs8ie.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - NEXTAUTH_SECRET=3318201bd0a188eba438d46881a85b86dd810ba04744e7ed3529c040ce76f185
      - BASE_URL=http://54.147.12.236:3000
      - NEXT_PUBLIC_API_KEY=AIzaSyAi2jpr9dxuwRRFnwmbDhWrZIIKGwWEdWs
      - NODE_ENV=production  # Set the environment to production
    restart: unless-stopped  # Automatically restart the container unless manually stopped
