apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_ID: 843731093025-0iooes2k63ir68cn0bvvqlb2h220f9qc.apps.googleusercontent.com # Enter your Google ID here in base64 encoded format
  GOOGLE_SECRET: R09DU1BYLVE2elYxemV5NkdjV2xsQzhYNEhCYXFkdG5Wazc=  # Enter your Google secret here in base64 encoded format
  NEXTAUTH_SECRET: Cst9orAxQM5h6BDwUnZiSEH4aw9juSMosDJ3x8LmdvQ= # Enter your NextAuth secret here in base64 encoded format
  NEXT_PUBLIC_API_KEY: QUl6YVN5QjFlME1TWjRTQ19tNDNqVWlzRGZ0MnA3bFBjcWVtM3Y4 # Enter your API key here in base64 encoded format
  MONGODB_URI: mongodb+srv://alipeco90_db_user:D7Xr4ExRbiavbE6K@cluster0.bnl24cv.mongodb.net/  # Enter your MongoDB URI here in base64 encoded format
