apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLTMzYWRsS1BJMUhnWXJ2cEhQZFA0MjJCbWo3b1c= # Enter your Google secret here in base64 encoded format
  NEXTAUTH_SECRET: ckhBU0wwaXNqZUxoemxzWUlDMGZSSE5NSE9qQVNoUFhWMkFRSkFHU3BJQT0= # Enter your NextAuth secret here in base64 encoded format
  NEXT_PUBLIC_API_KEY: QUl6YVN5QTNxUEt2RkNWQkpGUU56T3RRWWRiUGkwQkY5b3RmcDZZ # Enter your API key here in base64 encoded format