apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_ID: 843731093025-eol05fgfiajku69sg3b9opvuautbe07v.apps.googleusercontent.com # Enter your Google ID here in base64 encoded format
  GOOGLE_SECRET: R09DU1BYLThiNEI4TDhTZDY0UEE0LVhHNWFhQlNqZVZjVTk=  # Enter your Google secret here in base64 encoded format
  NEXTAUTH_SECRET: Wml6ZEFJck5TSUVGa2laQ2Q1d2hPc29YaStudm9DQkVSQjd6OHhoK0VXbz0K # Enter your NextAuth secret here in base64 encoded format
  NEXT_PUBLIC_API_KEY: QUl6YVN5QmxNeFo2TzBMelZ6eWxnWmI0MnBFQVdsMjNDUmdQSUVB # Enter your API key here in base64 encoded format
  MONGODB_URI: mongodb+srv://alipeco90_db_user:D7Xr4ExRbiavbE6K@cluster0.bnl24cv.mongodb.net/  # Enter your MongoDB URI here in base64 encoded format
