apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 103384355930-hifpmkea0j6gfuvnefkpvraq1junoauf.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://34.245.131.128.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
