apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLUNIbVN1Zk04U3lsUDlRNlRhazhKa1pvNVpOUzQ= # Enter your Google secret here in base64 encoded format
  NEXTAUTH_SECRET: 7mkoYHM3xl2QZZVMrzvT+gkSIxWUgbhNNkVc2nxkk2g= # Enter your NextAuth secret here in base64 encoded format
  NEXT_PUBLIC_API_KEY: QUl6YVN5RFRxSUxCRktZUjEzX2tkRkNrY0MwUmY0ODZ3c3QyQUww # Enter your API key here in base64 encoded format
  MONGODB_URI: c2h1YmhhbUAxMjM0 # Enter your MongoDB URI here in base64 encoded format
