apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_ID: MTAzMzg0MzU1OTMwLWhpZnBta2VhMGo2Z2Z1dm5lZmtwdnJhcTFqdW5vYXVmLmFwcHMuZ29vZ2xl
dXNlcmNvbnRlbnQuY29t # Enter your Google ID here in base64 encoded format
  GOOGLE_SECRET: R09DU1BYLU9GZ3ZxaWo3X1JXbWZYOTRYOS13UUJnUnZ4bTk= # Enter your Google secret here in base64 encoded format
  NEXTAUTH_SECRET: Qb8YA4ruozWvRotNqdC3thIjkjNkAkPuGGtAWy1etLQ= # Enter your NextAuth secret here in base64 encoded format
  NEXT_PUBLIC_API_KEY: QUl6YVN5QldaYUEwUEtqZ1o3cF9FOC1aX1NwMld6WF9ldi1LeGM0 # Enter your API key here in base64 encoded format
  MONGODB_URI: <enter-your-mongodb-uri> # Enter your MongoDB URI here in base64 encoded format
